import uuid
import copy

acdcFile =  {
           "lfn": "MCFakeFile-pdmvserv_task_SMP-RunIISummer15wmLHEGS-00226__v1_T_180407_003917_9963-SMP-RunIISummer15wmLHEGS-00226_0-7f9b849517efdc0f04d6e30007309241",
           "locations": [
               "T3_US_PuertoRico",
               "T2_FI_HIP",
               "T2_UK_SGrid_RALPP",
               "T3_US_Baylor",
               "T3_TW_NTU_HEP",
               "T0_CH_CERN_Disk",
               "T2_KR_KNU",
               "T2_RU_SINP",
               "T3_US_UMD",
               "T3_US_Colorado",
               "T1_UK_RAL_Disk",
               "T2_TH_CUNSTDA",
               "T3_US_Kansas",
               "T1_IT_CNAF_Disk",
               "T2_IT_Bari",
               "T2_US_UCSD",
               "T2_RU_IHEP",
               "T3_US_Vanderbilt_EC2",
               "T3_US_JHU",
               "T3_BY_NCPHEP",
               "T3_US_TTU",
               "T3_US_UCR",
               "T3_TW_NCU",
               "T2_CH_CSCS",
               "T2_UA_KIPT",
               "T2_PK_NCP",
               "T2_RU_PNPI",
               "T3_US_UCD",
               "T3_CO_Uniandes",
               "T3_KR_KNU",
               "T2_FR_IPHC",
               "T3_US_OSU",
               "T3_US_TAMU",
               "T2_CN_Beijing",
               "T2_UK_London_Brunel",
               "T3_IN_PUHEP",
               "T3_IT_Trieste",
               "T2_EE_Estonia",
               "T2_IN_TIFR",
               "T2_IT_Rome",
               "T2_US_Florida",
               "T3_GR_IASA_HG",
               "T3_US_Princeton_ICSE",
               "T3_US_Rutgers",
               "T2_US_Wisconsin",
               "T2_HU_Budapest",
               "T2_DE_RWTH",
               "T2_BR_SPRACE",
               "T2_CH_CERN",
               "T2_BR_UERJ",
               "T3_MX_Cinvestav",
               "T3_US_FNALLPC",
               "T3_RU_FIAN",
               "T3_US_Cornell",
               "T2_ES_IFCA",
               "T3_ES_Oviedo",
               "T3_US_NotreDame",
               "T2_DE_DESY",
               "T3_HU_Debrecen",
               "T2_US_Caltech",
               "T3_FR_IPNL",
               "T3_BG_UNI_SOFIA",
               "T1_RU_JINR_Disk",
               "T3_CN_PKU",
               "T2_UK_London_IC",
               "T2_US_Nebraska",
               "T2_ES_CIEMAT",
               "T1_FR_CCIN2P3_Disk",
               "T2_KR_KISTI",
               "T3_US_FSU",
               "T3_KR_UOS",
               "T3_IT_Perugia",
               "T1_ES_PIC_Disk",
               "T2_CH_CERNBOX",
               "T2_TR_METU",
               "T2_AT_Vienna",
               "T2_US_Purdue",
               "T3_US_Rice",
               "T2_TW_NCHC",
               "T2_BE_UCL",
               "T3_US_FIT",
               "T2_UK_SGrid_Bristol",
               "T2_PT_NCG_Lisbon",
               "T3_US_UMiss",
               "T2_IT_Legnaro",
               "T1_DE_KIT_Disk",
               "T2_RU_ITEP",
               "T3_US_SDSC",
               "T3_US_FIU",
               "T2_RU_JINR",
               "T2_IT_Pisa",
               "T2_GR_Ioannina",
               "T3_US_MIT",
               "T3_US_UCSB",
               "T2_MY_UPM_BIRUNI",
               "T2_FR_GRIF_IRFU",
               "T3_US_NERSC",
               "T2_FR_CCIN2P3",
               "T2_PL_Warsaw",
               "T2_US_MIT",
               "T2_BE_IIHE",
               "T2_RU_INR",
               "T2_PL_Swierk",
               "T3_CH_PSI",
               "T3_IT_Bologna"
           ],
           "first_event": 15443001,
           "checksums": {
           },
           "id": 7116520,
           "size": 0,
           "runs": [
               {
                   "run_number": 1,
                   "lumis": [
                       15444,
                       15445
                   ]
               }
           ],
           "last_event": 0,
           "parents": [
           ],
           "events": 1000,
           "merged": 0
       }

ACDC_FILES = []
baseLFN = acdcFile["lfn"]
for i in range(200000):
    newACDC = copy.deepcopy(acdcFile)
    newACDC["lfn"] = "%s-%s" % (baseLFN, uuid.uuid4())
    ACDC_FILES.append(newACDC)

